version: '3.3'
services:
  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    ports:
    - "80:80"
    restart: always
    volumes:
        - ./code:/var/www/html
    depends_on:
    - php-fpm
    - database

  adminer:
    build:
      context: ./adminer
      dockerfile: Dockerfile
    ports:
    - "8080:8080"
    restart: always
    depends_on:
    - database

  database:
    build:
          context: ./mysql
          dockerfile: Dockerfile
    ports:
    - "3306:3306"
    environment:
    - MYSQL_ROOT_PASSWORD=root
    - MYSQL_USER=manju
    - MYSQL_PASSWORD=4444

  php-fpm:
    build:
      context: ./php-fpm
      dockerfile: Dockerfile
    volumes:
    - ./code:/var/www/html
